[package]
name = "arti-hyper"
version = "0.0.4"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Adapter for making anonymos http requests using the Tor network and hyper"
keywords = [ "tor", "arti", "privacy", "anonymity", "hyper" ]
categories = [ "network-programming", "cryptography" ]
repository="https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = [ "native-tls" ]
native-tls = [ "arti-client/native-tls" ]
rustls = [ "arti-client/rustls" ]
static = [ "arti-client/static" ]

# Enable experimental APIs that are not yet officially supported.
#
# These APIs are not covered by semantic versioning.  Using this
# feature voids your "semver warrantee".
experimental-api = []

[dependencies]
arti-client = { path="../arti-client", version = "0.0.4"}
hyper = { version = "0.14", features = ["http1", "client", "runtime"] }

[dev-dependencies]
