[package]
name = "tor-rpc-connect"
version = "0.24.0"
edition = "2021"
rust-version = "1.77"
authors = ["The Tor Project, Inc."]
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Common implementation logic for Arti RPC Connect points"
keywords = ["tor", "arti", "rpc"]
categories = ["asynchronous"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
full = ["rpc-client", "rpc-server"]
default = []

rpc-client = []
rpc-server = ["tor-rtcompat"]

[dependencies]
# NOTE: This crate is a dependency of our RPC client library;
# Try to avoid introducing big unconditional dependencies!
fs-mistrust = { path = "../fs-mistrust", version = "0.8.0" }
serde = { version = "1.0.103", features = ["derive"] }
thiserror = "1"
toml = "0.8.8"
tor-basic-utils = { path = "../tor-basic-utils", version = "0.24.0" }
tor-config-path = { path = "../tor-config-path", version = "0.24.0", features = ["address"] }
tor-general-addr = { path = "../tor-general-addr", version = "0.24.0" }
tor-rtcompat = { path = "../tor-rtcompat", version = "0.24.0", optional = true }
tracing = "0.1.36"

[dev-dependencies]
assert_matches = "1.5.0"
tempfile = "3.10"
