[package]
name = "tor-netdir"
version = "0.0.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Types to represent and use a Tor network directory"
keywords = [ "tor", "arti" ]
categories = [ "network-programming" ]
repository="https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []
experimental-api = []
testing = [ "hex", "hex-literal", "tor-netdoc/build_docs" ]

[dependencies]
tor-checkable = { path="../tor-checkable", version="0.0.0" }
tor-netdoc = { path="../tor-netdoc", version="0.0.0" }
tor-linkspec = { path="../tor-linkspec", version="0.0.0" }
tor-llcrypto = { path="../tor-llcrypto", version="0.0.0" }
tor-protover = { path="../tor-protover", version="0.0.0" }
tor-units = { path="../tor-units", version="0.0.0" }

tracing = "0.1.26"
rand = "0.8.3"
serde = { version = "1.0.124", features = ["derive"] }
signature = "1.3.0"
thiserror = "1.0.24"
hex = { version= "0.4.3", optional = true }
hex-literal = { version= "0.3.1", optional = true }

[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.3.1"
tor-netdoc = { path="../tor-netdoc", version="0.0.0", features=["build_docs"] }
