[package]
name = "arti-rpcserver"
version = "0.0.1"
edition = "2021"
rust-version = "1.60"
authors = ["The Tor Project, Inc.", "eta <eta@torproject.org>"]
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Backend functionality for Arti's RPC service"
keywords = ["tor", "arti", "rpc"]
categories = ["asynchronous"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []
full = []

experimental = ["tokio"]
tokio = ["tokio-crate", "tokio-util"]

[dependencies]
arti-client = { path = "../arti-client", version = "0.8.2" }
asynchronous-codec = { version = "0.6.0", features = ["json"] }
bytes = "1"
erased-serde = "0.3.25"
futures = "0.3.14"
once_cell = "1"
pin-project = "1"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.50"
thiserror = "1"
tokio-crate = { package = "tokio", version = "1.7", optional = true, features = ["full"] }
tokio-util = { version = "0.7.0", features = ["compat"], optional = true }
tor-error = { path = "../tor-error", version = "0.4.1" }
tor-rpccmd = { path = "../tor-rpccmd", version = "0.0.1" }
tor-rtcompat = { path = "../tor-rtcompat", version = "0.8.1" }
tracing = "0.1.18"
typetag = "0.2.7"

[dev-dependencies]
futures-await-test = "0.3.0"
