[package]
name = "tor-relay-selection"
version = "0.0.1"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.70"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Logic to select Tor relays for specific purposes"
keywords = ["tor", "arti"]
categories = ["network-programming"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []
full = []

experimental = ["geoip"]
geoip = ["tor-geoip", "tor-netdir/geoip", "__is_experimental"]
__is_experimental = []

[dependencies]
tor-geoip = { path = "../tor-geoip", version = "0.2.0", optional = true }
tor-linkspec = { path = "../tor-linkspec", version = "0.11.0" }
tor-netdir = { path = "../tor-netdir", version = "0.12.0" }
tor-netdoc = { path = "../tor-netdoc", version = "0.12.0" }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
