# (Built-in defaults for the arti configuration format.)

# Default port to use when listening to SOCKS connections.  We always
# listen on localhost.
socks_port = 9150

# Whether to log at the "trace" debugging level.  By default, we log at
# "debug".
trace = false

# Locations to use for storing things on disk.
#
# These paths can use ~ to indicate the user's home directory, or a set
# of shell-style variables to indicate platform-specific paths.
#
# Supported variables are APP_CACHE, APP_CONFIG, APP_SHARED_DATA,
# APP_LOCAL_DATA, and USER_HOME.
[storage]
cache_dir = "${APP_CACHE}"
state_dir = "${APP_LOCAL_DATA}"

# Replacement values for consensus parameters.  This is an advanced option
# and you probably should leave it alone. Not all parameters are supported.
# These are case-sensitive.
#
#[override_net_params]
#circwindow = 1000
#min_paths_for_circs_pct = 60
