stages:
  - build
  - test

variables:
  # We don't need Husky to install the Git hooks for CI.
  CARGO_HUSKY_DONT_INSTALL_HOOKS: "true"

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose --target x86_64-unknown-linux-gnu
    - cargo test --verbose
    - rustup component add clippy rustfmt
    - cargo clippy --all-features --tests -- -D warnings
    - cargo fmt -- --check
    - cargo install cargo-audit
    - ./maint/cargo_audit.sh
  tags:
    - amd64
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/debug/arti
    expire_in: 1 hours

rust-latest-async-std:
  stage: build
  image: rust:latest
  script:
    - cd crates/arti-client && cargo check --no-default-features --features=async-std
  tags:
    - amd64

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  allow_failure: true
  script:
    - cargo build --verbose --target x86_64-unknown-linux-gnu --all-features
    - cargo test --verbose --all-features
    - rustup component add clippy
    - cargo clippy --all-features
    - RUSTDOCFLAGS="-Dwarnings" cargo doc --all-features --document-private-items
  tags:
    - amd64

build-repro:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null
  stage: build
  image: rust:1.54.0-alpine3.14
  script:
    - ./maint/reproducible_build.sh linux windows macos
  artifacts:
    paths:
      - arti-linux
      - arti-windows.exe
      - arti-macos
    expire_in: 1 day
  cache:
    paths:
      - osxcross/target
  tags:
    - TPA
    - amd64


integration:
  stage: test
  image: debian:stable-slim
  script:
    - apt update
    - apt install -y tor git python3 curl
    - ./tests/chutney/setup.sh
    - curl http://example.com -vs --socks5-hostname 127.0.0.1:9150 -o /dev/null
    - ./tests/chutney/teardown.sh
  tags:
    - amd64
