[workspace]

# Here we declare that this is a workspace, containing several crates
# within it.
members = [
    "caret",
    "tor-rtcompat",
    "tor-llcrypto",
    "tor-protover",
    "tor-bytes",
    "tor-socksproto",
    "tor-checkable",
    "tor-cert",
    "tor-linkspec",
    "tor-cell",
    "tor-proto",
    "tor-retry",
    "tor-netdoc",
    "tor-consdiff",
    "tor-netdir",
    "tor-chanmgr",
    "tor-circmgr",
    "tor-dirclient",
    "tor-dirmgr",
    "tor-config",
    "tor-client",
    "arti"
    ]
