disallowed-methods = [
    { path = "rand::Rng::gen_range", reason = "Prefer tor_basic_utils::RngExt::gen_range_checked to avoid uncontrolled panics, or gen_range_infallible if applicable" },
#    { path = "std::time::SystemTime::now", reason = "prefer using SleepProvider::wallclock instead when possible" },
]
