[package]
name = "tor-log-ratelim"
version = "0.0.1"
authors = ["The Tor Project, Inc."]
edition = "2021"
rust-version = "1.65"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Facility for rate-limiting log messages in Arti"
keywords = ["tor", "arti", "async"]
categories = ["asynchronous"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]

default = []

[dependencies]

event-listener = "3"
futures = "0.3.14"
humantime = "2"
once_cell = "1.18"
tor-error = "0.5.4"
tor-rtcompat = { path = "../tor-rtcompat", version = "0.9.5" }
tracing = "0.1.36"
weak-table = "0.3.0"

[dev-dependencies]
thiserror = "1"
