[package]
name = "tor-guardmgr"
version = "0.0.3"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Manage a set of guard relays for Tor network"
keywords = [ "tor", "arti", "async" ]
categories = [ "network-programming", "cryptography" ]
repository="https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []

# Enable testing-only APIs.  APIs under this feature are not
# covered by semver.
testing = []

[dependencies]
tor-config = { path="../tor-config", version = "0.0.3"}
tor-netdir = { path="../tor-netdir", version = "0.0.3"}
tor-linkspec = { path="../tor-linkspec", version = "0.0.3"}
tor-llcrypto = { path="../tor-llcrypto", version = "0.0.3"}
tor-persist = {  path="../tor-persist", version = "0.0.3"}
tor-proto = {  path="../tor-proto", version = "0.0.3", features=["traffic-timestamp"] }
tor-rtcompat = { path="../tor-rtcompat", version = "0.0.3"}
tor-units = { path="../tor-units", version = "0.0.3"}

derive_builder = "0.10"
futures = "0.3"
humantime-serde = "1"
itertools = "0.10.1"
pin-project = "1"
rand = "0.8"
serde = { version = "1.0.103", features = ["derive"] }
retain_mut = "0.1.3"
thiserror = "1"
tracing = "0.1.18"

[dev-dependencies]
tor-netdir = { path="../tor-netdir", version = "0.0.3", features=["testing"]}
tor-netdoc = { path="../tor-netdoc", version = "0.0.3"}
tor-persist = {  path="../tor-persist", version = "0.0.3", features=["testing"]}
tor-rtcompat = { path="../tor-rtcompat", version = "0.0.3", features=["tokio"]}
tor-rtmock = { path="../tor-rtmock", version = "0.0.3"}
