[package]
name = "tor-consdiff"
version = "0.0.0"
authors = ["Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[features]
default = []
slow-diff-apply = []

[dependencies]

tor-llcrypto = { path="../tor-llcrypto", version= "*" }

digest = "0.9.0"
hex = "0.4.2"
thiserror = "1.0.23"
