[package]
name = "tor-general-addr"
version = "0.24.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.77"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Generalized socket address type used by Tor"
keywords = ["tor", "arti", "async"]
categories = ["asynchronous"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []
full = ["arbitrary"]

[dependencies]
arbitrary = { version = "1.3.2", optional = true, features = ["derive"] }
derive_more = { version = "1.0.0", features = ["full"] }
thiserror = "1"
void = "1"

[dev-dependencies]
assert_matches = "1.5.0"

[package.metadata.docs.rs]
all-features = true
