[package]
name = "tor-memquota"
version = "0.27.0"
authors = ["The Tor Project, Inc.", "Ian Jackson <iwj@torproject.org>"]
edition = "2021"
rust-version = "1.77"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Memory use tracking and quota utilities, used by Tor software"
keywords = ["tor", "arti"]
categories = ["memory-management"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
derive-deftly = { version = "~1.0.0", features = ["full", "beta"] }
derive_more = { version = "2.0.1", features = ["full"] }
dyn-clone = "1.0.17"
educe = "0.4.6"
futures = "0.3.14"
itertools = "0.14.0"
paste = "1"
pin-project = "1"
serde = { version = "1.0.103", features = ["derive"] }
slotmap-careful = { path = "../slotmap-careful", version = "0.2.2" }
static_assertions = "1"
thiserror = "2"
tor-async-utils = { path = "../tor-async-utils", version = "0.27.0" }
tor-basic-utils = { path = "../tor-basic-utils", version = "0.27.0", features = ["serde"] }
tor-config = { path = "../tor-config", version = "0.27.0" }
tor-error = { path = "../tor-error", version = "0.27.0", features = ["tracing"] }
tor-log-ratelim = { path = "../tor-log-ratelim", version = "0.27.0" }
tor-rtcompat = { version = "0.27.0", path = "../tor-rtcompat" }
tracing = "0.1.36"
visibility = { version = "0.1.0", optional = true }
void = "1"

[dev-dependencies]
rand = "0.8"
safelog = { path = "../safelog", version = "0.4.2" }
serde_json = "1.0.50"
tor-basic-utils = { path = "../tor-basic-utils", version = "0.27.0" }
tor-rtcompat = { version = "0.27.0", path = "../tor-rtcompat", features = ["tokio", "native-tls"] }
tor-rtmock = { path = "../tor-rtmock", version = "0.27.0" }
tracing-test = "0.2.4"

[features]
full = [
    "memquota",
    "tor-config/full",
    "tor-error/full",
    "tor-log-ratelim/full",
    "tor-rtcompat/full",
    "tor-async-utils/full",
    "tor-basic-utils/full",
    "slotmap-careful/full",
]
default = ["memquota"]
memquota = []
testing = ["__is_experimental", "visibility"]
experimental = ["testing"]
__is_experimental = []
