[package]
name = "keygen-openssh-test"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["The Tor Project, Inc.", "Gabriela Moldovan <gabi@torproject.org>"]
rust-version = "1.77"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Tool used by arti to generate OpenSSH keys for testing"

[dependencies]
base32 = "0.5"
clap = { version = "4.3.24", features = ["derive"] }
rand = "0.9"
rand_core = { version = "0.9.3", features = ["getrandom"] }
ssh-key = { version = "0.6.1", features = ["dsa", "alloc", "rand_core", "std"] }
tor-basic-utils = { path = "../../crates/tor-basic-utils" }
tor-keymgr = { path = "../../crates/tor-keymgr", features = ["keymgr"] }
tor-llcrypto = { path = "../../crates/tor-llcrypto", features = ["relay", "cvt-x25519"] }

[features]
full = ["tor-basic-utils/full", "tor-keymgr/full", "tor-llcrypto/full"]
