[package]
name = "keygen-openssh-test"
version = "0.1.0"
edition = "2021"

[dependencies]
base32 = "0.4"
clap = { version = "4.3.24", features = ["derive"] }
rand = "0.8"
tor-llcrypto = { path = "../../crates/tor-llcrypto", features = ["relay", "cvt-x25519"] }
tor-keymgr = { path = "../../crates/tor-keymgr", features = ["keymgr"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
