[package]
name = "keygen-openssh-test"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["The Tor Project, Inc.", "Gabriela Moldovan <gabi@torproject.org>"]
rust-version = "1.70"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Tool used by arti to generate OpenSSH keys for testing"

[dependencies]
base32 = "0.4"
clap = { version = "4.3.24", features = ["derive"] }
rand = "0.8"
rand_core = { version = "0.6.4", features = ["getrandom"] }
tor-keymgr = { path = "../../crates/tor-keymgr", features = ["keymgr"] }
tor-llcrypto = { path = "../../crates/tor-llcrypto", features = ["relay", "cvt-x25519"] }
