[package]
name = "tor-socksproto"
version = "0.24.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.77"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Encode and decode the SOCKS protocol, as extended in Tor"
keywords = ["tor", "arti", "socks"]
categories = ["network-programming"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = ["proxy-handshake"]

client-handshake = []
proxy-handshake = []

full = ["proxy-handshake", "client-handshake", "caret/full", "tor-bytes/full", "tor-error/full", "safelog/full"]

[dependencies]
amplify = { version = "4", default-features = false, features = ["derive"] }
arbitrary = { version = "1.0.1", optional = true, features = ["derive"] }
caret = { path = "../caret", version = "0.5.0" }
derive-deftly = "0.14"
educe = "0.4.6"
safelog = { path = "../safelog", version = "0.4.1" }
subtle = "2"
thiserror = "1"
tor-bytes = { path = "../tor-bytes", version = "0.24.0", default-features = false }
tor-error = { path = "../tor-error", version = "0.24.0", default-features = false }

[dev-dependencies]
anyhow = "1.0.75"
hex-literal = "0.4"
[package.metadata.docs.rs]
all-features = true
