[package]
name = "tor-socksproto"
version = "0.7.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.65"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Encode and decode the SOCKS protocol, as extended in Tor"
keywords = ["tor", "arti", "socks"]
categories = ["network-programming"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = ["proxy-handshake"]

# XXXX Mark as full, experimental, or non-additive!
client-handshake = []

# XXXX Mark as full, experimental, or non-additive!

# XXXX This is reachable from 'default', but from 'full'.
proxy-handshake = []
full = ["caret/full", "tor-bytes/full", "tor-error/full"]

[dependencies]
arbitrary = { version = "1.0.1", optional = true, features = ["derive"] }
caret = { path = "../caret", version = "0.4.0" }
subtle = "2"
thiserror = "1"
tor-bytes = { path = "../tor-bytes", version = "0.7.0" }
tor-error = { path = "../tor-error", version = "0.5.0" }

[dev-dependencies]
hex-literal = "0.4"
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
