[package]
name = "tor-decompress"
version = "0.0.0"
authors = ["Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.38"
miniz_oxide = "0.4.3"
xz2 = "0.1.6"
zstd = "0.6.0"
