[package]
name = "arti-client"
version = "0.0.2"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Library for connecting to the Tor network as an anonymous client"
keywords = [ "tor", "arti", "privacy", "anonymity", "networking" ]
categories = [ "network-programming", "cryptography" ]
repository="https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = [ "tokio" ]
async-std = [ "tor-rtcompat/async-std" ]
tokio = [ "tor-rtcompat/tokio", "tor-proto/tokio" ]
static = [ "tor-rtcompat/static", "tor-dirmgr/static" ]

# Enable experimental APIs that are not yet officially supported.
#
# These APIs are not covered by semantic versioning.  Using this
# feature voids your "semver warrantee".
experimental-api = []

[dependencies]
tor-circmgr = { path="../tor-circmgr", version = "0.0.2"}
tor-config = { path="../tor-config", version = "0.0.2"}
tor-chanmgr = { path="../tor-chanmgr", version = "0.0.2"}
tor-dirmgr = { path="../tor-dirmgr", version = "0.0.2"}
tor-persist = { path="../tor-persist", version = "0.0.2"}
tor-proto = { path="../tor-proto", version = "0.0.2"}
tor-rtcompat = { path="../tor-rtcompat", version = "0.0.2"}

humantime-serde = "1.0.1"
derive_builder = "0.10.2"
directories = "4.0.1"
futures = "0.3.13"
tracing = "0.1.26"
serde = { version = "1.0.124", features = ["derive"] }
thiserror = "1.0.24"

[dev-dependencies]
tor-rtcompat = { path="../tor-rtcompat", version = "0.0.2", features=["tokio"] }
tokio-crate = { package = "tokio", version = "1.7.0", features = ["rt", "rt-multi-thread", "io-util", "net", "time", "macros" ] }
hyper = { version = "0.14.13", features = ["http1", "client", "runtime"] }
pin-project = { version = "1.0" }
tokio-util = { version = "0.6", features = ["compat"] }
anyhow = { version = "1.0" }
tracing-subscriber = "0.3.0"
