[package]
name = "arti-client"
version = "0.0.4"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Library for connecting to the Tor network as an anonymous client"
keywords = [ "tor", "arti", "privacy", "anonymity", "networking" ]
categories = [ "network-programming", "cryptography" ]
repository="https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = [ "tokio", "native-tls" ]
async-std = [ "tor-rtcompat/async-std" ]
tokio = [ "tor-rtcompat/tokio", "tor-proto/tokio" ]
native-tls = [ "tor-rtcompat/native-tls" ]
rustls = [ "tor-rtcompat/rustls" ]
static = [ "tor-rtcompat/static", "tor-dirmgr/static" ]

# Enable experimental APIs that are not yet officially supported.
#
# These APIs are not covered by semantic versioning.  Using this
# feature voids your "semver warrantee".
experimental-api = []

[dependencies]
tor-circmgr = { path="../tor-circmgr", version = "0.0.4"}
tor-config = { path="../tor-config", version = "0.0.4"}
tor-chanmgr = { path="../tor-chanmgr", version = "0.0.4"}
tor-dirmgr = { path="../tor-dirmgr", version = "0.0.4"}
tor-persist = { path="../tor-persist", version = "0.0.3"}
tor-proto = { path="../tor-proto", version = "0.0.4"}
tor-rtcompat = { path="../tor-rtcompat", version = "0.0.4"}

humantime-serde = "1"
derive_builder = "0.10"
derive_more = "0.99"
directories = "4"
futures = "0.3.14"
postage = { version = "0.4", default-features = false, features = ["futures-traits"] }
tracing = "0.1.18"
serde = { version = "1.0.103", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
tor-rtcompat = { path="../tor-rtcompat", version = "0.0.4", features=["tokio", "native-tls" ] }
tokio-crate = { package = "tokio", version = "1.4", features = ["rt", "rt-multi-thread", "io-util", "net", "time", "macros" ] }
hyper = { version = "0.14", features = ["http1", "client", "runtime"] }
pin-project = "1"
tokio-util = { version = "0.6", features = ["compat"] }
anyhow = "1.0.5"
tracing-subscriber = "0.3.0"
