[package]
name = "obfs4-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arti-client = { path = "../../crates/arti-client", features = [ "bridge-client", "pt-client", "experimental" ] }
tor-chanmgr = { path = "../../crates/tor-chanmgr", features = [ "pt-client", "experimental-api" ]}
tor-guardmgr = { path = "../../crates/tor-guardmgr" , features = [ "full" ]}
tokio = { version = "1.7", features = ["full"] }
tracing = "0.1"
tor-rtcompat = { path = "../../crates/tor-rtcompat" }
tor-proto = { path = "../../crates/tor-proto" }
tracing-subscriber = "0.2.0"
tls-api = "0.9.0"
tls-api-native-tls = "0.9.0"
tor-error = { path = "../../crates/tor-error" }
futures = "0.3.28"
serde = "1.0.180"
axum = "0.6.19"
serde_json = "1.0.104"
chrono = { version = "0.4.26", features = [ "serde" ] }
clap = { version = "4.3.21", features = [ "derive" ] }
anyhow = "1.0.72"
