[package]
name = "tor-circmgr"
version = "0.0.2"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Manage a set of anonymous circuits over the Tor network"
keywords = [ "tor", "arti", "async" ]
categories = [ "network-programming", "cryptography" ]
repository="https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
# Enable experimental APIs that are not yet officially supported.
#
# These APIs are not covered by semantic versioning.  Using this
# feature voids your "semver warrantee".
experimental-api = []

[dependencies]
tor-chanmgr = { path="../tor-chanmgr", version = "0.0.2"}
tor-config = { path="../tor-config", version = "0.0.2"}
tor-guardmgr = { path="../tor-guardmgr", version = "0.0.2"}
tor-netdir = { path="../tor-netdir", version = "0.0.2"}
tor-netdoc = { path="../tor-netdoc", version = "0.0.2"}
tor-proto = { path="../tor-proto", version = "0.0.2"}
retry-error = { path="../retry-error", version = "0.0.2"}
tor-linkspec = { path="../tor-linkspec", version = "0.0.2"}
tor-persist = {  path="../tor-persist", version = "0.0.2"}
tor-rtcompat = { path="../tor-rtcompat", version = "0.0.2"}

async-trait = "0.1.2"
bounded-vec-deque = "0.1"
derive_builder = "0.10"
futures = "0.3"
humantime-serde = "1"
itertools = "0.10.1"
tracing = "0.1.18"
pin-project = "1"
rand = "0.8"
serde = { version = "1.0.103", features = ["derive"] }
static_assertions = "1"
thiserror = "1"
weak-table = "0.3.0"

[dev-dependencies]
async_executors = { version = "0.4", default-features = false, features = [ "tokio_tp" ] }
futures-await-test = "0.3.0"
tor-rtmock = { path="../tor-rtmock", version = "0.0.2"}
tor-guardmgr = { path="../tor-guardmgr", version = "0.0.2", features=["testing"]}
tor-llcrypto = { path="../tor-llcrypto", version = "0.0.2"}
tor-netdir = { path="../tor-netdir", version = "0.0.2", features=["testing"] }
tor-persist = { path="../tor-persist", version = "0.0.2", features=["testing"] }
tor-rtcompat = { path="../tor-rtcompat", version = "0.0.2", features=["tokio"] }
