[package]
name = "tor-config"
version = "0.0.2"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Low-level configuration for the Arti Tor implementation"
keywords = ["tor", "arti"]
categories = ["config"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = ["expand-paths"]
expand-paths = ["shellexpand", "directories"]

[dependencies]
thiserror = "1.0.24"
derive_builder = "0.10.2"
once_cell = "1.7.2"
serde = { version = "1.0.124", features = ["derive"] }
shellexpand = { version = "2.1.0", optional = true }
tracing = "0.1.26"
directories = { version = "4.0.1", optional = true }

[dev-dependencies]
dirs = "4.0.0"
tracing-test = "0.2.1"
