[package]
name = "tor-hsclient"
version = "0.2.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.65"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Arti's implementation of an onion service client"
keywords = ["tor", "arti", "cryptography"]
categories = ["cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []
full = [
    "retry-error/full",
    "safelog/full",
    "tor-checkable/full",
    "tor-circmgr/full",
    "tor-config/full",
    "tor-dirclient/full",
    "tor-error/full",
    "tor-hscrypto/full",
    "tor-linkspec/full",
    "tor-llcrypto/full",
    "tor-netdir/full",
    "tor-netdoc/full",
    "tor-proto/full",
    "tor-rtcompat/full",
]

[dependencies]
async-trait = "0.1.2"
derive_more = "0.99.3"
educe = "0.4.6"
either = "1"
futures = "0.3.14"
postage = { version = "0.5.0", default-features = false, features = ["futures-traits"] }
rand = "0.8"
rand_core = "0.6.2"
retry-error = { path = "../retry-error", version = "0.4.0" }
safelog = { path = "../safelog", version = "0.3.0" }
slotmap = "1.0.6"
strum = { version = "0.24", features = ["derive"] }
thiserror = "1"
tor-checkable = { path = "../tor-checkable", version = "0.5.0" }
tor-circmgr = { version = "0.8.0", path = "../tor-circmgr", features = ["hs-client"] }
tor-config = { path = "../tor-config", version = "0.9.0" }
tor-dirclient = { path = "../tor-dirclient", version = "0.7.0", default-features = false, features = ["hs-client"] }
tor-error = { path = "../tor-error", version = "0.5.0", features = ["experimental-api"] }                            # TODO HS
tor-hscrypto = { version = "0.2.0", path = "../tor-hscrypto" }
tor-linkspec = { version = "0.7.0", path = "../tor-linkspec" }
tor-llcrypto = { version = "0.5.0", path = "../tor-llcrypto" }
tor-netdir = { version = "0.9.0", path = "../tor-netdir", features = ["hs-client"] }
tor-netdoc = { path = "../tor-netdoc", version = "0.7.0", features = ["hs-client"] }
tor-proto = { version = "0.10.0", path = "../tor-proto", features = ["send-control-msg"] }
tor-rtcompat = { version = "0.9.0", path = "../tor-rtcompat" }
tracing = "0.1.36"

[dev-dependencies]
humantime = "2"
tokio-crate = { package = "tokio", version = "1.7", features = ["full"] }
tor-async-utils = { path = "../tor-async-utils", version = "0.1.0" }
tor-basic-utils = { path = "../tor-basic-utils", version = "0.7.0" }
tor-chanmgr = { path = "../tor-chanmgr", version = "0.9.0" }
tor-circmgr = { version = "0.8.0", path = "../tor-circmgr", features = ["hs-client", "testing"] }
tor-guardmgr = { path = "../tor-guardmgr", version = "0.9.0", features = ["testing"] }
tor-netdir = { path = "../tor-netdir", version = "0.9.0", features = ["testing"] }
tor-netdoc = { path = "../tor-netdoc", version = "0.7.0", features = ["testing"] }
tor-persist = { path = "../tor-persist", version = "0.7.0", features = ["testing"] }
tor-rtcompat = { path = "../tor-rtcompat", version = "0.9.0", features = ["tokio", "native-tls"] }
tor-rtmock = { path = "../tor-rtmock", version = "0.8.0" }
tracing-test = "0.2"
