[package]
name = "tor-proto"
version = "0.0.4"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Asynchronous client-side implementation of the central Tor network protocols"
keywords = ["tor", "arti", "networking", "anonymity"]
categories = ["network-programming", "cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []
hs = []
ntor_v3 = []
tokio = ["tokio-crate", "tokio-util"]
traffic-timestamp = ["coarsetime"]

[dependencies]
tor-llcrypto = { path = "../tor-llcrypto", version = "0.0.3"}
tor-bytes = { path = "../tor-bytes", version = "0.0.3"}
tor-cert = { path = "../tor-cert", version = "0.0.3"}
tor-linkspec = { path = "../tor-linkspec", version = "0.0.3"}
tor-checkable = { path = "../tor-checkable", version = "0.0.3"}
tor-protover = { path = "../tor-protover", version = "0.0.3"}
tor-cell = { path = "../tor-cell", version = "0.0.3"}

arrayref = "0.3"
bytes = "1"
cipher = "0.3.0"
digest = "0.10.0"
futures = "0.3"
asynchronous-codec = "0.6.0"
generic-array = "0.14.3"
hkdf = "0.12.0"
hmac = "0.12.0"
tracing = "0.1.18"
rand = "0.8"
rand_core = "0.6.2"
subtle = "2"
thiserror = "1"
typenum = "1.12"
zeroize = "1"

tokio-crate = { package = "tokio", version = "1.4", optional = true }
tokio-util = { version = "0.6", features = ["compat"], optional = true }

coarsetime = { version = "0.1.20", optional = true }

[dev-dependencies]
tor-rtcompat = { path = "../tor-rtcompat", version = "0.0.4", features = [ "tokio", "native-tls" ] }
hex-literal = "0.3"
hex = "0.4"
