[package]
name = "tor-hspow"
version = "0.17.0"
authors = ["The Tor Project, Inc.", "Micah Elizabeth Scott <beth@torproject.org>"]
edition = "2021"
rust-version = "1.77"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Solve and verify proof-of-work client puzzles used by onion services"
keywords = ["tor", "arti", "cryptography"]
categories = ["cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

publish = false

[features]
default = []
hs-client = ["tor-netdoc/hs-client"]
hs-service = ["tor-netdoc/hs-service"]
full = [
    "hs-client",
    "hs-service",
    "equix/full"
]

[dependencies]
arrayvec = "0.7.4"
blake2 = "0.10.6"
derive_more = { version = "1.0.0", features = ["full"] }
equix = { path = "../equix", version = "0.2.0" }
rand = "0.8.5"
thiserror = "1"
tor-hscrypto = { version = "0.23.0", path = "../tor-hscrypto" }
tor-async-utils = { path = "../tor-async-utils", version = "0.23.0" }
tor-cell = { path = "../tor-cell", version = "0.23.0", features = ["hs"] }
tor-netdoc = { path = "../tor-netdoc", version = "0.23.0" }
tracing = "0.1.36"

[dev-dependencies]
hex-literal = "0.4.1"
