[package]
name = "tor-geoip"
version = "0.23.0"
authors = ["The Tor Project, Inc.", "eta <eta@torproject.org>"]
edition = "2021"
rust-version = "1.77"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "A crate to parse C Tor GeoIP CSV files."
keywords = ["tor", "arti"]
readme = "README.md"
categories = ["parser-implementations", "network-programming"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
derive_more = { version = "1.0.0", features = ["full"] }
once_cell = "1.18"
rangemap = "1.3"
thiserror = "1"

[features]
embedded-db = []
default = ["embedded-db"]
full = ["embedded-db"]
