[package]
name = "hashx-bench"
version = "0.0.0"
publish = false
edition = "2021"

[[bench]]
name = "hashx_bench"
harness = false

[dev-dependencies]
criterion = "0.5.1"
hashx = { path = "../" }
rand = "0.8.5"
tor-c-equix = { git = "https://gitlab.torproject.org/tpo/core/tor.git" }

[workspace]
members = ["."]
