[package]
name = "tor-keymgr"
version = "0.1.0"
authors = ["The Tor Project, Inc.", "Gabriela Moldovan <gabi@torproject.org>"]
edition = "2021"
rust-version = "1.65"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Key management for the Arti Tor implementation"
keywords = ["tor", "arti"]
categories = ["cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
derive_more = "0.99.3"
fs-mistrust = { path = "../fs-mistrust", version = "0.7.1", features = ["serde", "walkdir"] }
ssh-key = { version = "0.5.1", features = ["std"] }
thiserror = "1"
tor-error = { path = "../tor-error", version = "0.5.0" }
tor-hscrypto = { path = "../tor-hscrypto", version = "0.2.0" }
tor-llcrypto = { path = "../tor-llcrypto", version = "0.5.0" }
